In [48]:
import numpy as np

In [49]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (1.8.2)
Requirement already satisfied: black>=24.10.0 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (25.12.0)
Requirement already satisfied: bleach in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (0.1.13)
Requirement already satisfied: mypy>=1.15.0 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (1.19.1)
Requirement already satisfied: protobuf in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (6.33.2)
Requirement already satisfied: python-dateutil in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (80.9.0)
Requirement already satisfied: six>=1.10 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: tqdm in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: types-requests in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (2.32.4.20250913)
Requirement already satisfied: types-tqdm in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (4.67.0.20250809)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from kaggle) (2.6.2)
Requirement already satisfied: click>=8.0.0 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from black>=24.10.0->kaggle) (8.3.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from black>=24.10.0->kaggle) (1.1.0)
Requirement already satisfied: packaging>=22.0 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from black>=24.10.0->kaggle) (25.0)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from black>=24.10.0->kaggle) (0.12.1)
Requirement already satisfied: platformdirs>=2 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from black>=24.10.0->kaggle) (4.5.1)
Requirement already satisfied: pytokens>=0.3.0 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from black>=24.10.0->kaggle) (0.3.0)
Requirement already satisfied: colorama in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from click>=8.0.0->black>=24.10.0->kaggle) (0.4.6)
Requirement already satisfied: typing_extensions>=4.6.0 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from mypy>=1.15.0->kaggle) (4.15.0)
Requirement already satisfied: librt>=0.6.2 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from mypy>=1.15.0->kaggle) (0.7.4)
Requirement already satisfied: webencodings in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from requests->kaggle) (2025.11.12)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
!kaggle datasets list

ref                                                               title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
laveshjadon/ai-impact-on-students                                 Impact of Ai on Students                               1187170  2026-05-10 23:12:10.070000          17385        403                1
rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset    FIFA World Cup 2026 Player Performance Dataset         4154062  2026-06-10 12:58:47.093000           3776         79                1
sharmajicoder/used-car-price-prediction-dataset                   Used Car Price Prediction Dataset                     51728243  2026-06-13 17:05:48.793000           2291         45                1
mmumairkhattak/e-commerce-orders-dataset-2026-scra                E-commerce Orders Dataset 2026 | SCRA                  1796478  2026-06-11 06:56:56.550000           2327         45                1
nalisha/netflix-movies-and-tv-shows-data-analysis                 Netflix Movies and TV Shows Data Analysis              1783615  2026-05-28 11:58:01.040000           4511         94                1
mominullptr/fifa-world-cup-2026-dataset                           FIFA World Cup 2026 - Live Results & Updated Stats       67501  2026-06-25 16:43:27.420000           1188         40                1
sunil123kumar/social-media-impact-on-mental-health                Social_Media_Impact_on_Mental Health                     16190  2026-06-10 08:30:07.557000           1772         44                1
swaptr/fifa-wc-2026-players                                       FIFA World Cup 2026 Player Data                          56805  2026-06-25 19:01:56.673000           1203         36                1
raviiyadavv/house-price-predecition                               House_Price_Predecition                                  20085  2026-06-15 15:37:47.657000           1300         24       0.88235295
rupsarroy/heatwave-dataset-rajasthan-india-2006-2025              Heatwave Dataset (Rajasthan, India, 2006-2025)         1402909  2026-06-18 08:37:30.717000            412         27                1
lalit7881/comprehensive-car-market-analysis                       Comprehensive Car Market Analysis                       761719  2026-06-16 05:48:24.653000            692         20                1
cabcon/fifa-world-cup-2026-squad-lists-all-48-teams               FIFA World Cup 2026: Squad Lists (All 48 Teams)          48922  2026-06-14 22:54:44.427000            562         27                1
arjunmehta1992/chocolate-sales-in-20222023                        Chocolate Sales in 2022–2023                           4820417  2026-06-21 03:52:16.600000           1057         21                1
kulkarniparth09/fifa-world-cup-complete-dataset-19302026          FIFA World Cup Complete Dataset: 1930–2026               11953  2026-06-07 06:29:15.677000           2827         59                1
datasnaek/youtube-new                                             Trending YouTube Video Statistics                    210575746  2019-06-03 00:56:47.177000         307785       5946        0.7941176
velvetcrystal/fifa-world-cup-2026-complete-tournament-statistics  FIFA World Cup 2026 Complete Tournament Statistics      129266  2026-06-20 09:51:39.410000            546         35                1
zynicide/wine-reviews                                             Wine Reviews                                          53336293  2017-11-27 17:08:04.700000         355511       3877        0.7941176
nasa/kepler-exoplanet-search-results                              Kepler Exoplanet Search Results                        1215549  2017-10-10 18:26:59.497000          23445        865        0.8235294
datasnaek/chess                                                   Chess Game Dataset (Lichess)                           2903760  2017-09-04 03:09:09.453000          66165       1491        0.8235294
rtatman/188-million-us-wildfires                                  1.88 Million US Wildfires                            176270559  2020-05-12 21:03:49.213000          44786       1440        0.8235294

In [53]:
import json

with open(r"C:\Users\U S E R\.kaggle\kaggle.json") as f:
    data = json.load(f)

In [54]:
!kaggle datasets download -d dineshpiyasamara/sentiment-analysis-dataset

Dataset URL: https://www.kaggle.com/datasets/dineshpiyasamara/sentiment-analysis-dataset
License(s): unknown
sentiment-analysis-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [55]:
import zipfile

with zipfile.ZipFile("sentiment-analysis-dataset.zip", "r") as zip_ref:
    zip_ref.extractall("data")

In [57]:
import pandas as pd
import matplotlib.pyplot as plt

In [58]:
import os

os.listdir("data")

['sentiment_analysis.csv']

In [59]:
import pandas as pd

df = pd.read_csv("data/sentiment_analysis.csv")
df.head()

   id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

Data Preprocessing

In [60]:
df.shape

(7920, 3)

In [61]:
#duplicated
df.duplicated().sum()

np.int64(0)

In [62]:
#to see if there null values
df.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

Text Preprocessing

In [63]:
import re
import string

In [64]:
df["tweet"].head(5)

0    #fingerprint #Pregnancy Test https://goo.gl/h1...
1    Finally a transparant silicon case ^^ Thanks t...
2    We love this! Would you go? #talk #makememorie...
3    I'm wired I know I'm George I was made that wa...
4    What amazing service! Apple won't even talk to...
Name: tweet, dtype: object

#converting to lower case

In [65]:
df["tweet"]=df["tweet"].str.lower()
df.head()

   id  label                                              tweet
0   1      0  #fingerprint #pregnancy test https://goo.gl/h1...
1   2      0  finally a transparant silicon case ^^ thanks t...
2   3      0  we love this! would you go? #talk #makememorie...
3   4      0  i'm wired i know i'm george i was made that wa...
4   5      1  what amazing service! apple won't even talk to...

#links commars symbols,numbers no need))
import re
import re

df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'https?://\S+|www\.\S+', '', str(x)))  # Remove URLs
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'@\w+', '', x))                        # Remove @mentions
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'#', '', x))                           # Remove # symbol
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))                 # Remove punctuation & numbers
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'\s+', ' ', x).strip())
df["tweet"]=df["tweet"].apply(lambda x:re.sub(r'\d+','',str(x)))
# Remove extra spaces

In [66]:
df.head(5)

   id  label                                              tweet
0   1      0  #fingerprint #pregnancy test https://goo.gl/h1...
1   2      0  finally a transparant silicon case ^^ thanks t...
2   3      0  we love this! would you go? #talk #makememorie...
3   4      0  i'm wired i know i'm george i was made that wa...
4   5      1  what amazing service! apple won't even talk to...

Removing symbols and numbers

In [91]:
import re

df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'https?://\S+|www\.\S+', '', str(x)))  # Remove URLs
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'@\w+', '', x))                        # Remove @mentions
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'#', '', x))                           # Remove # symbol
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))                 # Remove punctuation & numbers
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'\s+', ' ', x).strip())
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'\d+', '', str(x)))
df["tweet"] = df["tweet"].apply(lambda x: re.sub(r'\s+', ' ', x).strip())
# Remove extra spaces

In [92]:
df.tail(10)

        id  label                                              tweet
7910  7911      0  perfect match instagood applewatch red instagr...
7911  7912      0      complet love new iphon emojis iphon appl emoj
7912  7913      0  tune in turn on drop out gtd one app mobil min...
7913  7914      1  ok galaxi crash one day wait til monday skyroc...
7914  7915      0  gain follow rt must follow follow back follow ...
7915  7916      0  live loud lol liveoutloud selfi smile soni mus...
7916  7917      0  would like wish amaz day make everi minut coun...
7917  7918      0  help love year old neighbor ipad morn made rea...
7918  7919      0  final got smart pocket wifi stay connect anyti...
7919  7920      0  appl barcelona appl store bcn barcelona travel...

Remove stopwords

In [93]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\u s e r\appdata\local\programs\python\python314\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [94]:
#downloading stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\U S E
[nltk_data]     R\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [96]:
from nltk.corpus import stopwords

In [97]:
#loading english stopwords
stop_words = set(stopwords.words('english'))

In [98]:
#remove stopwords 
df["tweet"] = df["tweet"].apply(
    lambda x: " ".join([word for word in str(x).split() if word not in stop_words])
)

In [99]:
df.head()

   id  label                                              tweet
0   1      0  fingerprint pregnanc test android app beauti c...
1   2      0  final transpar silicon case thank uncl yay son...
2   3      0  love would go talk makememori unplug relax iph...
3   4      0  wire know georg made way iphon cute daventri home
4   5      1  amaz service appl even talk question unless pa...

Stemming

In [100]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

df["tweet"] = df["tweet"].apply(
    lambda x: " ".join(ps.stem(word) for word in str(x).split())
)

In [101]:
df.head()

   id  label                                              tweet
0   1      0  fingerprint pregnanc test android app beauti c...
1   2      0  final transpar silicon case thank uncl yay son...
2   3      0  love would go talk makememori unplug relax iph...
3   4      0  wire know georg made way iphon cute daventri home
4   5      1  amaz servic appl even talk question unless pay...

Vocabulary (Getting Words)

In [102]:
 df.tail()

        id  label                                              tweet
7915  7916      0  live loud lol liveoutloud selfi smile soni mus...
7916  7917      0  would like wish amaz day make everi minut coun...
7917  7918      0  help love year old neighbor ipad morn made rea...
7918  7919      0  final got smart pocket wifi stay connect anyti...
7919  7920      0  appl barcelona appl store bcn barcelona travel...

Building Vocabulary

In [107]:
from collections import Counter
vocab=Counter()

In [108]:
vocab

Counter()

In [112]:
for sentence in df['tweet']:
    vocab.update(sentence.split())

In [114]:
len(vocab) #no of uniqe words

14195